#include <map>

#include <SFML/Graphics.hpp>


enum class LWJGLKeyboardCode {
    Unknown = -1,
    Num1 = 0x02,
    Num2 = 0x03,
    Num3 = 0x04,
    Num4 = 0x05,
    Num5 = 0x06,
    Num6 = 0x07,
    Num7 = 0x08,
    Num8 = 0x09,
    Num9 = 0x0A,
    Num0 = 0x0B,
    A = 0x1E,
    B = 0x30,
    C = 0x2E,
    D = 0x20,
    E = 0x12,
    F = 0x21,
    G = 0x22,
    H = 0x23,
    I = 0x17,
    J = 0x24,
    K = 0x25,
    L = 0x26,
    M = 0x32,
    N = 0x31,
    O = 0x18,
    P = 0x19,
    Q = 0x10,
    R = 0x13,
    S = 0x1F,
    T = 0x14,
    U = 0x16,
    V = 0x2F,
    W = 0x11,
    X = 0x2D,
    Y = 0x15,
    Z = 0x2C,
    Apostrophe = 0x28,
    At = 0x91,
    Back = 0x0E,
    Backslash = 0x2B,
    Capital = 0x3A,
    Colon = 0x92,
    Comma = 0x33,
    Enter = 0x1C,
    Equals = 0x0D,
    Grave = 0x29,
    Lbracket = 0x1A,
    Lcontrol = 0x1D,
    Lmenu = 0x38,
    Lshift = 0x2A,
    Minus = 0x0C,
    Numlock = 0x45,
    Pause = 0xC5,
    Period = 0x34,
    Rbracket = 0x1B,
    Rcontrol = 0x9D,
    Rmenu = 0xB8,
    Rshift = 0x36,
    Scroll = 0x46,
    Semicolon = 0x27,
    Slash = 0x35,
    Space = 0x39,
    Stop = 0x95,
    Tab = 0x0F,
    Underline = 0x93,
    // Keypad (and numpad with numlock off)
    Up = 0xC8,
    Down = 0xD0,
    Left = 0xCB,
    Right = 0xCD,
    End = 0xCF,
    Home = 0xC7,
    Pageup = 0xC9,
    Pagedown = 0xD1,
    Insert = 0xD2,
    Delete = 0xD3,
    // Function keys
    F1 = 0x3B,
    F2 = 0x3C,
    F3 = 0x3D,
    F4 = 0x3E,
    F5 = 0x3F,
    F6 = 0x40,
    F7 = 0x41,
    F8 = 0x42,
    F9 = 0x43,
    F10 = 0x44,
    F11 = 0x57,
    F12 = 0x58,
    F13 = 0x64,
    F14 = 0x65,
    F15 = 0x66,
    F16 = 0x67,
    F17 = 0x68,
    F18 = 0x69,
    F19 = 0x71,
    // Japanese keyboards
    Kana = 0x70,
    Kanji = 0x94,
    Convert = 0x79,
    Noconvert = 0x7B,
    Yen = 0x7D,
    Circumflex = 0x90,
    Ax = 0x96,
    // Numpad
    Numpad0 = 0x52,
    Numpad1 = 0x4F,
    Numpad2 = 0x50,
    Numpad3 = 0x51,
    Numpad4 = 0x4B,
    Numpad5 = 0x4C,
    Numpad6 = 0x4D,
    Numpad7 = 0x47,
    Numpad8 = 0x48,
    Numpad9 = 0x49,
    Numpadmul = 0x37,
    Numpaddiv = 0xB5,
    Numpadsub = 0x4A,
    Numpadadd = 0x4E,
    Numpaddecimal = 0x53,
    Numpadcomma = 0xB3,
    Numpadenter = 0x9C,
    Numpadequals = 0x8D,
};


std::map<sf::Keyboard::Key, LWJGLKeyboardCode> keymap {
    {sf::Keyboard::A, LWJGLKeyboardCode::A},
    {sf::Keyboard::B, LWJGLKeyboardCode::B},
    {sf::Keyboard::C, LWJGLKeyboardCode::C},
    {sf::Keyboard::D, LWJGLKeyboardCode::D},
    {sf::Keyboard::E, LWJGLKeyboardCode::E},
    {sf::Keyboard::F, LWJGLKeyboardCode::F},
    {sf::Keyboard::G, LWJGLKeyboardCode::G},
    {sf::Keyboard::H, LWJGLKeyboardCode::H},
    {sf::Keyboard::I, LWJGLKeyboardCode::I},
    {sf::Keyboard::J, LWJGLKeyboardCode::J},
    {sf::Keyboard::K, LWJGLKeyboardCode::K},
    {sf::Keyboard::L, LWJGLKeyboardCode::L},
    {sf::Keyboard::M, LWJGLKeyboardCode::M},
    {sf::Keyboard::N, LWJGLKeyboardCode::N},
    {sf::Keyboard::O, LWJGLKeyboardCode::O},
    {sf::Keyboard::P, LWJGLKeyboardCode::P},
    {sf::Keyboard::Q, LWJGLKeyboardCode::Q},
    {sf::Keyboard::R, LWJGLKeyboardCode::R},
    {sf::Keyboard::S, LWJGLKeyboardCode::S},
    {sf::Keyboard::T, LWJGLKeyboardCode::T},
    {sf::Keyboard::U, LWJGLKeyboardCode::U},
    {sf::Keyboard::V, LWJGLKeyboardCode::V},
    {sf::Keyboard::W, LWJGLKeyboardCode::W},
    {sf::Keyboard::X, LWJGLKeyboardCode::X},
    {sf::Keyboard::Y, LWJGLKeyboardCode::Y},
    {sf::Keyboard::Z, LWJGLKeyboardCode::Z},
    {sf::Keyboard::Num0, LWJGLKeyboardCode::Num0},
    {sf::Keyboard::Num1, LWJGLKeyboardCode::Num1},
    {sf::Keyboard::Num2, LWJGLKeyboardCode::Num2},
    {sf::Keyboard::Num3, LWJGLKeyboardCode::Num3},
    {sf::Keyboard::Num4, LWJGLKeyboardCode::Num4},
    {sf::Keyboard::Num5, LWJGLKeyboardCode::Num5},
    {sf::Keyboard::Num6, LWJGLKeyboardCode::Num6},
    {sf::Keyboard::Num7, LWJGLKeyboardCode::Num7},
    {sf::Keyboard::Num8, LWJGLKeyboardCode::Num8},
    {sf::Keyboard::Num9, LWJGLKeyboardCode::Num9},
    {sf::Keyboard::Escape, LWJGLKeyboardCode::Unknown},
    {sf::Keyboard::LControl, LWJGLKeyboardCode::Lcontrol},
    {sf::Keyboard::LShift, LWJGLKeyboardCode::Lshift},
    {sf::Keyboard::LAlt, LWJGLKeyboardCode::Lmenu},
    {sf::Keyboard::LSystem, LWJGLKeyboardCode::Unknown},
    {sf::Keyboard::RControl, LWJGLKeyboardCode::Rcontrol},
    {sf::Keyboard::RShift, LWJGLKeyboardCode::Rshift},
    {sf::Keyboard::RAlt, LWJGLKeyboardCode::Rmenu},
    {sf::Keyboard::RSystem, LWJGLKeyboardCode::Unknown},
    {sf::Keyboard::Menu, LWJGLKeyboardCode::Unknown},
    {sf::Keyboard::LBracket, LWJGLKeyboardCode::Lbracket},
    {sf::Keyboard::RBracket, LWJGLKeyboardCode::Rbracket},
    {sf::Keyboard::SemiColon, LWJGLKeyboardCode::Semicolon},
    {sf::Keyboard::Comma, LWJGLKeyboardCode::Comma},
    {sf::Keyboard::Period, LWJGLKeyboardCode::Period},
    {sf::Keyboard::Quote, LWJGLKeyboardCode::Apostrophe},
    {sf::Keyboard::Slash, LWJGLKeyboardCode::Slash},
    {sf::Keyboard::BackSlash, LWJGLKeyboardCode::Backslash},
    {sf::Keyboard::Tilde, LWJGLKeyboardCode::Grave},
    {sf::Keyboard::Equal, LWJGLKeyboardCode::Equals},
    {sf::Keyboard::Dash, LWJGLKeyboardCode::Minus},
    {sf::Keyboard::Space, LWJGLKeyboardCode::Space},
    {sf::Keyboard::Return, LWJGLKeyboardCode::Enter},
    {sf::Keyboard::BackSpace, LWJGLKeyboardCode::Back},
    {sf::Keyboard::Tab, LWJGLKeyboardCode::Tab},
    {sf::Keyboard::PageUp, LWJGLKeyboardCode::Pageup},
    {sf::Keyboard::PageDown, LWJGLKeyboardCode::Pagedown},
    {sf::Keyboard::End, LWJGLKeyboardCode::End},
    {sf::Keyboard::Home, LWJGLKeyboardCode::Home},
    {sf::Keyboard::Insert, LWJGLKeyboardCode::Insert},
    {sf::Keyboard::Delete, LWJGLKeyboardCode::Delete},
    {sf::Keyboard::Add, LWJGLKeyboardCode::Numpadadd},
    {sf::Keyboard::Subtract, LWJGLKeyboardCode::Numpadsub},
    {sf::Keyboard::Multiply, LWJGLKeyboardCode::Numpadmul},
    {sf::Keyboard::Divide, LWJGLKeyboardCode::Numpaddiv},
    {sf::Keyboard::Left, LWJGLKeyboardCode::Left},
    {sf::Keyboard::Right, LWJGLKeyboardCode::Right},
    {sf::Keyboard::Up, LWJGLKeyboardCode::Up},
    {sf::Keyboard::Down, LWJGLKeyboardCode::Down},
    {sf::Keyboard::Numpad0, LWJGLKeyboardCode::Numpad0},
    {sf::Keyboard::Numpad1, LWJGLKeyboardCode::Numpad1},
    {sf::Keyboard::Numpad2, LWJGLKeyboardCode::Numpad2},
    {sf::Keyboard::Numpad3, LWJGLKeyboardCode::Numpad3},
    {sf::Keyboard::Numpad4, LWJGLKeyboardCode::Numpad4},
    {sf::Keyboard::Numpad5, LWJGLKeyboardCode::Numpad5},
    {sf::Keyboard::Numpad6, LWJGLKeyboardCode::Numpad6},
    {sf::Keyboard::Numpad7, LWJGLKeyboardCode::Numpad7},
    {sf::Keyboard::Numpad8, LWJGLKeyboardCode::Numpad8},
    {sf::Keyboard::Numpad9, LWJGLKeyboardCode::Numpad9},
    {sf::Keyboard::F1, LWJGLKeyboardCode::F1},
    {sf::Keyboard::F2, LWJGLKeyboardCode::F2},
    {sf::Keyboard::F3, LWJGLKeyboardCode::F3},
    {sf::Keyboard::F4, LWJGLKeyboardCode::F4},
    {sf::Keyboard::F5, LWJGLKeyboardCode::F5},
    {sf::Keyboard::F6, LWJGLKeyboardCode::F6},
    {sf::Keyboard::F7, LWJGLKeyboardCode::F7},
    {sf::Keyboard::F8, LWJGLKeyboardCode::F8},
    {sf::Keyboard::F9, LWJGLKeyboardCode::F9},
    {sf::Keyboard::F10, LWJGLKeyboardCode::F10},
    {sf::Keyboard::F11, LWJGLKeyboardCode::F11},
    {sf::Keyboard::F12, LWJGLKeyboardCode::F12},
    {sf::Keyboard::F13, LWJGLKeyboardCode::F13},
    {sf::Keyboard::F14, LWJGLKeyboardCode::F14},
    {sf::Keyboard::F15, LWJGLKeyboardCode::F15},
    {sf::Keyboard::Pause, LWJGLKeyboardCode::Pause},
    {sf::Keyboard::Unknown, LWJGLKeyboardCode::Unknown}
};
